name: CI
on: pull_request
jobs:
  test:
    name: Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Install dependencies
        run: ls -la ~/.npm/ && npm i
      - name: Lint (JavaScript)
        run: npm run lint
      - name: Unit Tests (Browser)
        run: |
          ls -la ~/.npm/
          [[ -f ~/.npm/\@brightspace-ui/testing/text$((GITHUB_ATTEMPT_NUM - 1)).txt ]] && cat ~/.npm/\@brightspace-ui/testing/text$((GITHUB_ATTEMPT_NUM - 1)).txt
          touch ~/.npm/\@brightspace-ui/testing/text_$GITHUB_ATTEMPT_NUM.txt
          echo 'test' > ~/.npm/\@brightspace-ui/testing/text_$GITHUB_ATTEMPT_NUM.txt
          npm run test:browser
      - name: Unit Tests (Server)
        run: npm run test:server
