name: CI
on: pull_request
jobs:
  test:
    name: Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: BrightspaceUI/actions/test-data@dgleckler/test-data
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint (JavaScript)
        run: npm run lint
      - name: Unit Tests (Browser)
        run: npm run test:browser:ctor
      - name: Unit Tests (Server)
        run: npm run test:server
