name: CI
on: pull_request
jobs:
  test:
    name: Test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Cache Test Data
        uses: bearfriend/third-party-actions@patch-2
        id: d2l-test-data
        with:
          path: .d2l-test
          key: ${{ github.run_id }}-${{ github.run_attempt }}
          save-always: true
      - name: Install dependencies
        run: npm ci
      - name: Lint (JavaScript)
        run: npm run lint
      - name: Unit Tests (Browser)
        run: npm run test:browser
      - name: Unit Tests (Server)
        run: npm run test:server
