name: publish-markdown-docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - '**.md'
  workflow_call:
jobs:
  create_docs:
    uses: Brightspace/github-readme-to-confluence-action/.github/workflows/publish_docs.yml@main
    secrets:
      envConfluenceToken: ${{ secrets.CONFLUENCE_TOKEN }}
