name: vdiff
on: pull_request
jobs:
  vdiff:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Cache Test Data
        uses: bearfriend/third-party-actions@patch-2
        id: d2l-test-data
        with:
          path: .d2l-test
          key: ${{ github.run_id }}-${{ github.run_attempt }}
          save-always: true
      - name: Install dependencies
        run: npm ci
      - name: vdiff Tests
        uses: BrightspaceUI/actions/vdiff@main
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-config: ./test/browser/vdiff.config.js
